### ISSUE TITLE
Bitcurator disk image access tool not exporting files

### ISSUE THREAD

**Issue by nvanderperren** [BitCurator/bitcurator-distro-tools#2]
Hi,

We recently updated to the new Bitcurator version that is no longer distributed via an ISO. We now encounter the problem that it's no longer possible to export files with the disk image access tools. I can see the a list of files, I can select and deselect files, but when I click on export, it does nothing.

It seems I'm not the only one with this problem:
* https://groups.google.com/g/bitcurator-users/c/uBs8uhXu1mg
* https://groups.google.com/g/bitcurator-users/c/drrm9mTu9fo/m/YDzCvFaLBgAJ
* https://groups.google.com/g/bitcurator-users/c/ysLjSb_920w/m/dk6lnLIwDAAJ

**Comment by kamwoods** [comment]
Which version of BitCurator are you referring to?  In 2.2.18, the Disk
Image Access tool currently passes our tests, bringing up a "Find or create
output directory" dialog when clicking on the "Export Selections" tab and
exporting files from some sample fat16, fat32, NTFS, and ext4 volumes. A
couple of possibilities:

- The tool will not export files from file systems that TSK is not capable
of parsing. How is your disk image packaged (raw, ewf, etc) and what
filesystem(s) does it contain?
- Deleted files (colored red in the interface) may or may not be recoverable

You can try running the tool from the command line by typing
"bc_disk_access_v2.py" and seeing if you get any debug/error feedback, as
well.

**Comment by nvanderperren** [comment]
Ha, today I'm able to export files. Not sure why (maybe I also had selected deleted files or system files that couldn't be exported), but it's great that it's working now. My disk images were raw files and we have 2.2.16. The file system of the disks were FAT12 and FAT16.
